### ISSUE TITLE
Add Research Engineering README template?

### ISSUE THREAD

**Issue by jelletreep** [UtrechtUniversity/README-Templates#1]
Hi maintainers, great initiative! 

For research engineering projects we have a [project template repository](https://github.com/UtrechtUniversity/rse-project-templates/blob/master/README-template.md) including a README template. If it fits the scope of your collection I would be happy to submit a pull request (or feel free to just add a link or a copy).
Let me know!

**Comment by gspeed0689** [comment]
Hi Jelle, 

I think that is within the scope of this repository. Can you open a pull request placing it in the UU Code READMEs directory?
https://github.com/UtrechtUniversity/README-Templates/tree/main/CodeREADMEs/UU

**Comment by jelletreep** [comment]
Sure! Forking is disabled, so I am not able to open a pull request. Could you allow forking?

**Comment by gspeed0689** [comment]
I am unable to enable forking, that appears to be an organizational setting:
https://docs.github.com/en/organizations/managing-organization-settings/managing-the-forking-policy-for-your-organization

**Comment by jelletreep** [comment]
Ah I see. It should be possible for public repositories though. Does it make sense to switch visibility to public?
Otherwise you would have to add me as contributor or copy the readme template from my account (this is a clone, a PR is only possible for forks):
https://github.com/jelletreep/README-Templates

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by gspeed0689** [comment]
I had made it internal just to get started, but there's enough content in there that I made it public. So now a fork should be possible.
